# -*- coding: utf-8 -*-
"""DataPreProcessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y1TtGCyOWS6rHWIVGj23nWYWSWDOpgmN

Data Cleaning
"""

# import libraries
import pandas as pd
import matplotlib.pyplot as plt

# mount google drive
from google.colab import drive
drive.mount('/content/drive')

# load salary data into dataframe
df_salaries = pd.read_csv('/content/drive/MyDrive/DSCI 550 Project/Dataset/salaries_nov24.csv')
df_salaries.head(10)

# check for nulls
df_salaries.isnull().sum(axis=0)

# view job titles
pd.set_option('display.max_rows', None)
title_counts = df_salaries['job_title'].value_counts()
title_counts

# define bins and the titles that fall into each
title_bins = {
    'Data Scientist': [
        'Data Scientist', 'Applied Scientist', 'Associate', 'Consultant', 'Applied Data Scientist', 'Decision Scientist', 'Data Specialist',
        'Data Strategist', 'Principal Data Scientist', 'Staff Data Scientist', 'AI Data Scientist', 'Master Data Specialist',
        'Marketing Data Scientist'
    ],
    'Data Engineer': [
        'Data Engineer', 'Engineer', 'Data Architect', 'Data Modeler', 'Data Infrastructure Engineer',
        'Data Developer', 'Data Operations Engineer', 'Infrastructure Engineer', 'Data Integration Specialist', 'Data Integration Engineer',
        'Data Integration Developer', 'DataOps Engineer', 'Data Integration Analyst', 'Clinical Data Operator', 'Cloud Data Engineer',
        'Data Integration Coordinator', 'Principal Data Engineer', 'Data DevOps Engineer', 'Software Data Engineer', 'Azure Data Engineer',
        'Big Data Architect', 'Big Data Engineer', 'Big Data Developer', 'Data Platform Engineer', 'Data Pipeline Engineer', 'Consultant Data Engineer',
        'Cloud Data Architect', 'Platform Data Engineer', 'Principal Data Architect', 'Marketing Data Engineer', 'BI Data Engineer', 'AWS Data Architect',
        'ETL Developer', 'ETL Engineer', 'Cloud Database Engineer', 'Cloud Engineer', 'Cloud Developer', 'Cloud Database Administrator',
        'Developer', 'Principal Application Delivery Consultant'
    ],
    'BI and Data Analyst': [
        'Data Analyst', 'Analytics Engineer', 'Analyst', 'Business Intelligence Engineer', 'Business Intelligence Analyst',
        'Business Intelligence', 'Business Intelligence Developer', 'BI Developer', 'Business Analyst', 'BI Analyst',
        'Insight Analyst', 'BI Engineer', 'Power BI Developer', 'Data Analytics Specialist', 'Data Reporting Analyst',
        'Data Operations Analyst', 'Quantitative Analyst', 'Data Visualization Analyst', 'Business Data Analyst',
        'Data Analytics Consultant', 'BI Data Analyst', 'Business Intelligence Specialist', 'Data Visualization Specialist',
        'Data Operations Specialist', 'Data Operations Associate', 'Data Integrity Analyst', 'Data Visualization Developer',
        'Marketing Analyst', 'Data Analytics Associate', 'Actuarial Analyst', 'Data Analytics Developer', 'Analytics Specialist',
        'Admin & Data Analyst', 'Data Analytics Engineer', 'Financial Data Analyst', 'Finance Data Analyst', 'Staff Data Analyst',
        'Power BI Administrator', 'Power BI Consultant', 'Compliance Data Analyst', 'Marketing Data Analyst', 'Business Intelligence Data Analyst',
        'Power BI Architect', 'Pricing Analyst', 'Business Intelligence Consultant', 'Principal Data Analyst', 'People Data Analyst',
        'CRM Data Analyst', 'Sales Data Analyst', 'QA Engineer'
    ],
    'Software Engineer': [
        'Software Engineer', 'Software Intelligence Engineer', 'Software Developer', 'Backend Engineer', 'Full Stack Engineer',
        'Full Stack Developer', 'Full Stack Engineer', 'Robotics Software Engineer', 'Frontend Engineer', 'Software Architect',
        'Backend Software Engineer', 'Software Development Engineer', 'Fullstack Engineer'
    ],
    'Artificial Intelligence Engineer': [
        'AI Engineer', 'AI Architect', 'AI Developer', 'AI Scientist', 'AI Specialist', 'Artificial Intelligence Engineer',
        'AI Software Engineer', 'AI Solution Architect', 'AI Programmer', 'AI Machine Learning Engineer', 'AI Software Development Engineer'
    ],
    'Machine Learning Engineer': [
        'Machine Learning Engineer', 'Machine Learning Scientist', 'MLOps Engineer', 'Machine Learning Infrastructure Engineer',
        'Machine Learning Developer', 'ML Infrastructure Engineer', 'Machine Learning Model Engineer', 'Machine Learning Platform Engineer',
        'Machine Learning Software Engineer', 'Machine Learning Quality Engineer', 'Applied Machine Learning Scientist',
        'Machine Learning Architect', 'Machine Learning Modeler', 'Applied Machine Learning Engineer', 'Principal Machine Learning Engineer',
        'Machine Learning Specialist', 'Machine Learning Performance Engineer', 'Staff Machine Learning Engineer'
    ],
    'Data Governance Manager': [
        'Data Manager', 'Data Governance Manager', 'Data Management Analyst', 'Data Quality Analyst', 'Data Management Specialist', 'Data Governance Analyst',
        'Data Governance Specialist', 'Encounter Data Management Professional', 'Data Quality Engineer', 'Data Quality Manager', 'Data Quality Specialist',
        'Data Governance Engineer', 'Data Management Consultant', 'Master Data Management', 'Data Management Associate', 'Data Governance Architect',
        'Master Data Management'
    ],
    'Product Manager': [
        'Product Manager', 'Data Product Manager', 'Product Analyst', 'Data Product Owner', 'Product Designer', 'AI Product Owner',
        'Product Data Analyst', 'Data Product Analyst', 'AI Product Manager'
    ],
    'Specialist Engineer': [
        'Computer Vision Engineer',
        'Security Engineer', 'Robotics Engineer', 'Prompt Engineer', 'Site Reliability Engineer', 'Solutions Engineer', 'Solutions Architect',
        'Data Visualization Engineer', 'NLP Engineer', 'Deep Learning Engineer', 'Platform Engineer', 'DevOps Engineer', 'Systems Engineer',
        'Bear Robotics', 'Computer Vision Software Engineer', 'Chatbot Developer', 'System Engineer', 'Solution Engineer', 'SAS Developer',
        'Technical Specialist', 'Machine Vision Engineer', 'Databricks Engineer', 'Solution Architect', 'Python Developer'
    ],
    'Reseacher': [
        'Research Scientist', 'Research Engineer', 'Research Analyst', 'Machine Learning Researcher', 'Quantitative Researcher',
        'AI Researcher', 'Research Associate', 'Research Assistant', 'AI Research Engineer', 'Machine Learning Research Engineer',
        'AI Research Scientist', 'Deep Learning Researcher', 'Applied Research Scientist', 'Quantitative Research Analyst',
    ],
    'Statistician': [
        'Statistician', 'Statistical Programmer', 'Principal Statistical Programmer'
    ],
    'Manager/Lead': [
        'Manager', 'Engineer Manager', 'Head of Data', 'Data Analytics Manager', 'Data Analytics Lead', 'Data Lead', 'Technical Lead',
        'Data Governance Lead', 'Business Intelligence Manager', 'Lead Engineer', 'Analytics Lead', 'Data Quality Lead', 'Data Operations Manager',
        'Data Team Lead', 'Director of Machine Learning', 'Head of AI', 'Data Management Lead', 'Machine Learning Manager', 'Lead Data Scientist',
        'Data Strategy Lead', 'Head of Machine Learning', 'AI Lead', 'Data Management Manager', 'Data Strategy Manager', 'Lead Data Engineer',
        'Lead Data Analyst', 'Lead Machine Learning Engineer', 'Data Scientist Lead', 'Data Analyst Lead', 'Machine Learning Lead', 'Applied AI ML Lead',
        'Marketing Analytics Manager', 'Data Analytics Team Lead', 'Head of Business Intellgience', 'Director of Business Intelligence',
        'Data Operations Lead', 'Data Science Tech Lead', 'AI Engineering Manager', 'Lead AI Engineer', 'Analytics Engineering Manager',
        'Engineering Manager', 'Business Intelligence Lead', 'Manager Data Management', 'Head of Business Intelligence'
    ],
    'Other': [
        'Member of Technical Staff', 'Computational Biologist', 'Bioinformatics Scientist', 'Technical Writer',
        'Stage', 'Elasticsearch Administrator', 'Autonomous Vehical Technician', 'Postdoctoral Fellow'
    ],
}

# function to categorize each title
def categorize_job(title):
    for category, titles in title_bins.items():
        if title in titles:
            return category
    return 'Other'

# bin titles
df_salaries.insert(df_salaries.columns.get_loc('job_title') + 1, 'job_title_cleaned', df_salaries['job_title'].apply(categorize_job))
df_salaries.head(10)

# get top 9 countries and replace all others with 'Other'
top_9_countries = df_salaries['employee_residence'].value_counts().nlargest(9).index
df_salaries['employee_residence'] = df_salaries['employee_residence'].apply(lambda x: x if x in top_9_countries else 'Other')
df_salaries['company_location'] = df_salaries['company_location'].apply(lambda x: x if x in top_9_countries else 'Other')

# save cleaned data to CSV
df_salaries.to_csv('cleaned_salaries_nov24.csv', index=False)

"""Data Visualization"""

# calculate the value counts for each job title
job_title_counts = df_salaries['job_title_cleaned'].value_counts().sort_values(ascending=True)
job_title_counts

# plot bar chart for job title distribution
plt.figure(figsize=(10, 8))
job_title_counts.plot(kind='barh')
plt.xlabel('Count')
plt.ylabel('Job Title')
plt.title('Distribution of Job Titles')
plt.show()

# scatter plot of all salaries
plt.figure(figsize=(10, 8))
plt.scatter(df_salaries['job_title_cleaned'], df_salaries['salary_in_usd'], alpha=0.6)
plt.xlabel('Job Title')
plt.ylabel('Salary in USD')
plt.title('Salaries by Job Title')
plt.xticks(rotation=90)
plt.show()

# calculate avg salary for each job title
df_avg_salaries = df_salaries.groupby('job_title_cleaned')['salary_in_usd'].mean().sort_values(ascending=False).reset_index()
df_avg_salaries.columns = ['job_title', 'average_salary_in_usd']
df_avg_salaries

# plot vertical bar chart for avg salaries
plt.figure(figsize=(10, 8))
plt.bar(df_avg_salaries['job_title'], df_avg_salaries['average_salary_in_usd'])
plt.xlabel('Job Title')
plt.ylabel('Average Salary in USD')
plt.title('Average Salary by Job Title')
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

# plot horizontal bar chart for avg salaries
plt.figure(figsize=(10, 8))
plt.barh(df_avg_salaries['job_title'], df_avg_salaries['average_salary_in_usd'])
plt.ylabel('Job Title')
plt.xlabel('Average Salary in USD')
plt.title('Average Salary by Job Title')
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()